/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.dqm.controller;import cn.zhuatech.dqm.common.ApiResponse;import cn.zhuatech.dqm.service.DataProductReleaseService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                        */
@RestController @RequestMapping("/api/enterprise/dqm")public class DataProductReleaseController{private final DataProductReleaseService service;/**
                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                        */
public DataProductReleaseController(DataProductReleaseService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/data-product-release")public ApiResponse<DataProductReleaseService.Assessment>assess(@Valid @RequestBody DataProductReleaseService.Request request){return ApiResponse.ok(service.assess(request));}}
