/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.dqm.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                            */
class DataProductReleaseServiceTest{private final DataProductReleaseService service=new DataProductReleaseService();/**
                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                */
@Test void publishesTrustedProduct(){var r=service.assess(new DataProductReleaseService.Request("DP1",true,true,true,true,0,true,96,10,30));assertThat(r.decision()).isEqualTo(DataProductReleaseService.Decision.PUBLISH);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
@Test void blocksGovernanceFailures(){var r=service.assess(new DataProductReleaseService.Request("DP2",false,false,false,false,2,false,96,10,30));assertThat(r.blockers()).hasSize(6);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@Test void reviewsQualityAndFreshness(){var r=service.assess(new DataProductReleaseService.Request("DP3",true,true,true,true,0,true,80,60,30));assertThat(r.actions()).hasSize(2);}}
